export const byteBazaarProducts = [
  "Printer",
  "Scanner",
  "Laptop",
  "Monitor",
  "Keyboard",
  "Mouse",
  "Projector",
  "Fax machine",
  "Calculator",
  "Shredder",
  "Photocopier",
  "Whiteboard",
  "Paper shredder",
  "Desk lamp",
  "External hard drive",
  "Conference phone",
  "Label maker",
  "Document camera",
  "Wireless presenter",
  "USB hub",
];
